### PR TITLE
Resolve type references

### PR DESCRIPTION
**Pull request by uxmal**
New PR for you; all unit tests are passing and common code has been refactored.

### CODE REVIEW

**Comment by ptomin** [comment]
Build failed: https://travis-ci.org/uxmal/reko/builds/101694847
/home/travis/build/uxmal/reko/src/Environments/SysV/SysV.csproj: error : Command 'mono /home/travis/build/uxmal/reko/src/tools/c2xml/bin/TravisRelease/c2xml.exe -a x86-protected-32 -e elf-neutral libc.so.inc > libc.so.xml' exited with code: 255.

**Comment by uxmal** [comment]
I'm working to resolve this; it's made difficult by the lack of diagnostics in the Travis build process. In the meanwhile, see if the PR gets you further in being apply to supply user data types.

**Comment by ptomin** [comment]
I will test it tonight. As for build error you can reproduce it without Travis: just run 
mono /tmp/reko/src/tools/c2xml/bin/Debug/c2xml.exe -a x86-protected-32 -e elf-neutral libc.so.inc
on Linux

**Comment by uxmal** [comment]
Wow. Your comment above clued me into what is wrong with the build. The path you entered is incorrect. I will be fixing that shortly. Thanks! <g>

**Comment by uxmal** [comment]
Confirmed; the build is fine again.

**Comment by ptomin** [comment]
1. I have added unit tests
2. When analyse data flow doing I catched exception : "Illegal cross-thread operation: Control 'treeBrowser' accessed from a thread other than the thread it was created on."
   The reason is the line number 65 at file UserSignatureBuilder : 
   proc.Name = sProc.Name;

**Comment by uxmal** [comment]
(2.) Which unit test is failing, exactly?

**Comment by uxmal** [comment]
By the way, all unit tests pass on my (Windows) machine.

**Comment by ptomin** [comment]
No, they are passed

**Comment by uxmal** [comment]
Oh, you mean when you run the Reko shell and try decompiling an image?

**Comment by uxmal** [comment]
Mundanely, I have to go to fix dinner; I'll be gone for a couple of hours. In the meantime, could you give me the user-specified C that is causing the exception you're seeing?

**Comment by ptomin** [comment]
To reproduce:
Use WindowsDecompiler. Scan Binaries then Analyse Dataflow
I think the failure does not depend on which signature is set. I set "BYTE test(BYTE a, BYTE b)"
You may try to set  "int test(int a, int b)"

**Comment by ptomin** [comment]
Also it is reproduced on snowman-51

**Comment by uxmal** [comment]
OK, the uxmal/reko/resolve-type-references is now updated to fix this. Let me know if anything else is broken. If OK, maybe it's time to merge this into Master?

**Pull request merged**
